#!/usr/bin/env python3

from __future__ import annotations

import ast
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CORE = ROOT / "core_v2"
DOCS = ROOT / "docs"
OUTPUT = DOCS / "DEVELOPER_SNAPSHOT.md"


def git(*args: str) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def signature(node: ast.AST) -> str:
    try:
        return ast.unparse(node)
    except Exception:
        return node.name


def analyse_file(path: Path) -> dict:
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(path))

    imports: list[str] = []
    classes: list[dict] = []
    functions: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.Import):
            imports.extend(
                alias.name
                for alias in node.names
            )

        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            imports.append(
                f"{node.level * '.'}{module}"
            )

        elif isinstance(node, ast.ClassDef):
            methods: list[str] = []

            for item in node.body:
                if isinstance(
                    item,
                    (ast.FunctionDef, ast.AsyncFunctionDef),
                ):
                    if not item.name.startswith("_"):
                        methods.append(signature(item))

            classes.append(
                {
                    "name": node.name,
                    "bases": [
                        signature(base)
                        for base in node.bases
                    ],
                    "dataclass": any(
                        (
                            isinstance(dec, ast.Name)
                            and dec.id == "dataclass"
                        )
                        or (
                            isinstance(dec, ast.Attribute)
                            and dec.attr == "dataclass"
                        )
                        for dec in node.decorator_list
                    ),
                    "methods": methods,
                }
            )

        elif isinstance(
            node,
            (ast.FunctionDef, ast.AsyncFunctionDef),
        ):
            if not node.name.startswith("_"):
                functions.append(signature(node))

    return {
        "imports": sorted(set(imports)),
        "classes": classes,
        "functions": functions,
    }


def build_snapshot() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)

    files = sorted(CORE.glob("*.py"))
    analyses = {
        path: analyse_file(path)
        for path in files
    }

    branch = git("branch", "--show-current")
    commit = git(
        "log",
        "-1",
        "--format=%h %s",
    )

    milestone = "Unknown"

    progress = DOCS / "PROJECT_PROGRESS.md"
    if progress.exists():
        text = progress.read_text(encoding="utf-8")

        for line in text.splitlines():
            if "M17" in line:
                milestone = line.strip()
                break

    lines: list[str] = []

    lines.extend(
        [
            "# AI_BRIDGE V2 — Developer Snapshot",
            "",
            "> Automatically generated by "
            "`tools/build_developer_snapshot.py`.",
            "",
            "## Repository",
            "",
            f"- Root: `{ROOT}`",
            f"- Branch: `{branch}`",
            f"- Last commit: `{commit}`",
            f"- Current milestone: `{milestone}`",
            "",
            "## Files",
            "",
        ]
    )

    for path in files:
        relative = path.relative_to(ROOT)
        lines.append(f"- `{relative}`")

    lines.extend(
        [
            "",
            "## Public API",
            "",
        ]
    )

    for path in files:
        relative = path.relative_to(ROOT)
        data = analyses[path]

        lines.append(f"### `{relative}`")
        lines.append("")

        if data["imports"]:
            lines.append("**Imports**")
            lines.append("")
            for item in data["imports"]:
                lines.append(f"- `{item}`")
            lines.append("")

        if data["classes"]:
            lines.append("**Classes**")
            lines.append("")

            for cls in data["classes"]:
                marker = " — dataclass" if cls["dataclass"] else ""
                lines.append(
                    f"- `{cls['name']}`{marker}"
                )

                if cls["bases"]:
                    lines.append(
                        "  - Bases: "
                        + ", ".join(
                            f"`{base}`"
                            for base in cls["bases"]
                        )
                    )

                if cls["methods"]:
                    lines.append(
                        "  - Public methods:"
                    )
                    for method in cls["methods"]:
                        lines.append(
                            f"    - `{method}`"
                        )

            lines.append("")

        if data["functions"]:
            lines.append("**Public functions**")
            lines.append("")

            for function in data["functions"]:
                lines.append(f"- `{function}`")

            lines.append("")

    lines.extend(
        [
            "## Module Dependencies",
            "",
        ]
    )

    for path in files:
        relative = path.relative_to(ROOT)
        data = analyses[path]

        core_imports = [
            item
            for item in data["imports"]
            if item.startswith("core_v2")
        ]

        if core_imports:
            lines.append(
                f"- `{relative}` → "
                + ", ".join(
                    f"`{item}`"
                    for item in core_imports
                )
            )

    lines.extend(
        [
            "",
            "## Generation",
            "",
            "Command:",
            "",
            "```bash",
            "python3 tools/build_developer_snapshot.py",
            "```",
            "",
        ]
    )

    OUTPUT.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    print(f"Generated: {OUTPUT}")


if __name__ == "__main__":
    build_snapshot()
