#!/usr/bin/env python3

from __future__ import annotations

import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docs/research/AGENT_REGISTRY.json"
BASELINE = ROOT / "sandbox/agent_lab/baseline"
STATE = ROOT / "docs/SESSION_STATE.md"


def run(*cmd: str) -> str:
    return subprocess.check_output(
        cmd,
        cwd=ROOT,
        text=True,
        stderr=subprocess.DEVNULL,
    ).strip()


def main() -> int:
    branch = run("git", "branch", "--show-current")
    head = run("git", "rev-parse", "--short", "HEAD")
    commits = run("git", "log", "--oneline", "-5")

    core = all((ROOT / "core_v2").glob("*.py"))
    baseline = (BASELINE / "main_v2.py").exists()

    registry = False
    agents = 0

    if REGISTRY.exists():
        data = json.loads(REGISTRY.read_text(encoding="utf-8"))
        candidates = data.get("candidates", [])
        agents = len(candidates)
        registry = True

    registry_status = "PASS" if registry else "FAIL"

    status = run("git", "status", "--short")
    lines = status.splitlines() if status else []

    STATE.parent.mkdir(parents=True, exist_ok=True)
    STATE.write_text(
        f"""# AI_BRIDGE V3 — SESSION STATE

Generated by tools/project_state.py.

## Repository
- root: {ROOT}
- branch: {branch}
- head: {head}
- working_tree_entries: {len(lines)}

## Integrity
- core_v2: {"PASS" if core else "FAIL"}
- baseline: {"PASS" if baseline else "FAIL"}
- sandbox: {"PASS" if BASELINE.exists() else "FAIL"}
- agent_registry: {registry_status}

## Agents
- candidates: {agents}

## Milestone
- current: M16.5 — Continuity Automation
- next: AGENT_SANDBOX

## Rules
- Repository = source of truth
- Git = authoritative history
- Chat = temporary interface
- external agents = RESEARCH_ONLY
- core_v2 = protected
- experiments = sandbox
- validation = mandatory
- rollback = mandatory
- promotion = controlled
- paid services = forbidden

## Recent commits
{commits}

## Current status
{status if status else "CLEAN"}
""",
        encoding="utf-8",
    )

    print("AI_BRIDGE V3 STATE")
    print(f"branch: {branch}")
    print(f"head: {head}")
    print(f"core: {'PASS' if core else 'FAIL'}")
    print(f"baseline: {'PASS' if baseline else 'FAIL'}")
    print(f"sandbox: {'PASS' if BASELINE.exists() else 'FAIL'}")
    print(f"agents: {agents}")
    print(f"registry: {registry_status}")
    print(f"working_tree_entries: {len(lines)}")
    print("session_state: UPDATED")
    print("milestone: M16.5")
    print("next: AGENT_SANDBOX")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
