"""
Memory engine for AI_BRIDGE V2.

The memory engine stores runtime information generated by the AI_BRIDGE
V2 pipeline.

This baseline implementation keeps all records in memory using only
Python standard library components.

Only the Python standard library is used.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class MemoryRecord:
    """Single record stored by the memory engine."""

    category: str
    data: dict[str, Any]


@dataclass(slots=True)
class MemorySnapshot:
    """Snapshot of the current memory state."""

    records: list[MemoryRecord] = field(default_factory=list)


class MemoryEngine:
    """AI_BRIDGE V2 memory engine."""

    def __init__(self) -> None:
        self._records: list[MemoryRecord] = []

    def store(self, record: MemoryRecord) -> None:
        """Store a new record."""

        self._records.append(record)

    def last_record(self) -> MemoryRecord | None:
        """Return the most recently stored record."""

        if not self._records:
            return None

        return self._records[-1]

    def snapshot(self) -> MemorySnapshot:
        """Return a snapshot of all stored records."""

        return MemorySnapshot(records=list(self._records))

    def clear(self) -> None:
        """Remove every stored record."""

        self._records.clear()

    @property
    def size(self) -> int:
        """Return the number of stored records."""

        return len(self._records)
